apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hightower-workspaces
  namespace: hightower
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 10Gi
