{{- if .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hightower.serviceAccountName" . }}
  labels:
    {{- include "hightower.labels" . | nindent 4 }}
{{- end }}
