apiVersion: v1
kind: Service
metadata:
  name: {{ include "hightower.api.fullname" . }}
  labels:
    {{- include "hightower.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "hightower.api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
