apiVersion: v1
kind: Service
metadata:
  name: {{ include "hightower.temporal.serviceName" . }}
  labels:
    {{- include "hightower.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "hightower.temporal.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.temporal.ports.grpc }}
      targetPort: {{ .Values.temporal.ports.grpc }}
    - name: web-ui
      port: {{ .Values.temporal.ports.webUi }}
      targetPort: {{ .Values.temporal.ports.webUi }}
