apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hightower.fullname" . }}-workspaces
  labels:
    {{- include "hightower.labels" . | nindent 4 }}
  {{- if .Values.workspaces.retain }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    - {{ .Values.workspaces.accessMode }}
  storageClassName: {{ .Values.workspaces.storageClass }}
  resources:
    requests:
      storage: {{ .Values.workspaces.size }}
