apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shannon-api
  namespace: shannon
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "delete", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shannon-api
  namespace: shannon
subjects:
  - kind: ServiceAccount
    name: shannon-api
    namespace: shannon
roleRef:
  kind: Role
  name: shannon-api
  apiGroup: rbac.authorization.k8s.io
